In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset=pd.read_csv('emotions.csv')

In [ ]:
dataset = dataset.drop(columns=['Clean_Text','Unnamed: 0'])

In [ ]:
dataset.head()

Emotion                                               Text
0  neutral                                             Why ? 
1      joy    Sage Act upgrade on my to do list for tommorow.
2  sadness  ON THE WAY TO MY HOMEGIRL BABY FUNERAL!!! MAN ...
3      joy   Such an eye ! The true hazel eye-and so brill...
4      joy  @Iluvmiasantos ugh babe.. hugggzzz for u .!  b...

In [ ]:
dataset.shape

(34792, 2)

In [ ]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 34792):
  text = re.sub('[^a-zA-Z]', ' ', dataset['Text'][i])
  text = text.lower()
  text = text.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  text = [ps.stem(word) for word in text if not word in set(all_stopwords)]
  text = ' '.join(text)
  corpus.append(text)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()

In [ ]:
y = dataset.iloc[:, 0].values

In [ ]:
y

array(['neutral', 'joy', 'sadness', ..., 'anger', 'fear', 'sadness'],
      dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 472   13   49  165   38  114    1   23]
 [  25   41   11   41    4   42    0    7]
 [  86   11  667  199   22  101    0   37]
 [  87   15   83 1620   77  169    0  104]
 [  15    1   11   92  317   30    0    5]
 [  92   12   68  326   49  698    2   43]
 [   0    0    1    2    0    3   20    0]
 [  54   13   46  313   26   91    0  305]]


0.5949130622215836

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34792 entries, 0 to 34791
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Emotion  34792 non-null  object
 1   Text     34792 non-null  object
dtypes: object(2)
memory usage: 543.8+ KB


In [ ]:
# Sample input
x1 = "This book was so interesting it made me happy"

# Assuming 'classifier' is your pre-built and pre-trained model
# and 'cv' is your fitted CountVectorizer

def prediction(ex1):
    # Ensure the input is a string
    ex1 = str(ex1)

    # Text preprocessing
    new_text = re.sub('[^a-zA-Z]', ' ', ex1)
    new_text = new_text.lower()
    new_text = new_text.split()

    ps = PorterStemmer()
    all_stopwords = stopwords.words('english')
    all_stopwords.remove('not')

    new_text = [ps.stem(word) for word in new_text if word not in set(all_stopwords)]
    new_text = ' '.join(new_text)

    # Transform the input text
    X_prediction = cv.transform([new_text]).toarray()

    # Predict using the pre-trained classifier
    y_prediction = classifier.predict(X_prediction)
    return y_prediction

# Run the prediction function
print(prediction(x1))

['joy']


In [ ]:
import pickle
filename='train_model.sav'
pickle.dump(classifier,open(filename,'wb'))
loaded_model=pickle.load(open('train_model.sav','rb'))

In [ ]:
with open('count_vectorizer.pkl', 'wb') as f:
    pickle.dump(cv, f)

Now we will make a predictive system using the loaded model

In [ ]:
x1 = "This book was so interesting it made me happy"

# Assuming 'classifier' is your pre-built and pre-trained model
# and 'cv' is your fitted CountVectorizer

def prediction(ex1):
    # Ensure the input is a string
    ex1 = str(ex1)

    # Text preprocessing
    new_text = re.sub('[^a-zA-Z]', ' ', ex1)
    new_text = new_text.lower()
    new_text = new_text.split()

    ps = PorterStemmer()
    all_stopwords = stopwords.words('english')
    all_stopwords.remove('not')

    new_text = [ps.stem(word) for word in new_text if word not in set(all_stopwords)]
    new_text = ' '.join(new_text)

    # Transform the input text
    X_prediction = cv.transform([new_text]).toarray()

    # Predict using the pre-trained loaded model
    y_prediction = loaded_model.predict(X_prediction)
    return y_prediction

# Run the prediction function
print(prediction(x1))

['joy']
